services:
  postgres_container:
    image: postgres:latest
    ports:
      - "5544:5432" # Porta alterada para evitar conflito
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nimbledb
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "-f", "pg_isready -U postgres"]
      start_period: 60s
      interval: 30s
      timeout: 5s
      retries: 3
      disable: false
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 256m

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 256m

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: 
      -config.file=/etc/loki/local-config.yaml
      -print-config-stderr=true

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail-pagamento
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./pagamento-logs:/var/log/pagamento:ro
      - ./src/main/resources/promtail-config.yml:/etc/promtail/config.yml:ro
      - ./src/main/resources:/positions
    depends_on:
      - loki

volumes:
  postgres_data:
  pagamento-logs:
  promtail-positions:
