global:
  scrape_interval: 10s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "nimble-gateway"
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "nimble-pagamento"
    scrape_interval: 5s
    metrics_path: "/nimble-pagamento/api/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]
